-- --------------------------------------------------------------------------------
-- Routine DDL
-- Note: comments before and after the routine body will not be stored by the server
-- --------------------------------------------------------------------------------
DELIMITER $$

CREATE PROCEDURE addSales(
	in_salesUID VARCHAR(45), 
  in_userUID VARCHAR(45), 
  in_companyUID VARCHAR(45), 
  in_addedBy VARCHAR(45), 
  
  in_RevPanel VARCHAR(45),
  in_CltID VARCHAR(45),
  in_CltBill VARCHAR(45),
  in_CltInv VARCHAR(45),
  in_CltScrn VARCHAR(45),
  in_CltGST VARCHAR(45),
  in_CltStmt VARCHAR(45),
  in_CltLgl VARCHAR(45),
  in_CltCrBu VARCHAR(45),
  in_CltClosed VARCHAR(45),
  in_CltTrust VARCHAR(45),
  in_CltBank VARCHAR(45),
  in_CltTransit VARCHAR(45),
  in_CltAcct VARCHAR(45),
  in_CltNo VARCHAR(45),
  in_CltGrpNo VARCHAR(45),
  in_CltCt1 VARCHAR(45),
  in_CltCt1Title VARCHAR(45),
  in_CltCt1Note VARCHAR(45),
  in_CltName VARCHAR(45),
  in_CltCt2 VARCHAR(45),
  in_CltCt2Title VARCHAR(45),
  in_CltCt2Note VARCHAR(45),
  in_CltAdd1 VARCHAR(45),
  in_CltCt3 VARCHAR(45),
  in_CltCt3Title VARCHAR(45),
  in_CltCt3Note VARCHAR(45),
  in_CltAdd2 VARCHAR(45),
  in_CltInstructions VARCHAR(45),
  in_CltCity VARCHAR(45),
  in_CltProv VARCHAR(45),
  in_CltPCod VARCHAR(45),
  in_CltTel1 VARCHAR(45),
  in_CltFax VARCHAR(45),
  in_CltEmlPm VARCHAR(45),
  in_CltReview VARCHAR(45),
  in_CltRefNum VARCHAR(45),
  in_CltEmIn VARCHAR(45),
  in_CltTel2 VARCHAR(45),
  in_CltEmail VARCHAR(45),
  in_CltViciList VARCHAR(45),
  in_CltTel3 VARCHAR(45),
  in_CltACH VARCHAR(45),
  in_SalesNoteSum VARCHAR(45),
  in_CltImportSpec VARCHAR(45),
  in_CltIntDeferred VARCHAR(45),
  in_SalesStatus VARCHAR(45),
  in_CltComRate VARCHAR(45),
  in_CltSales VARCHAR(45),
  in_CltWorked VARCHAR(45),
  in_CltSpcStats VARCHAR(45),
  in_CltPrefCol VARCHAR(45),
  in_CltIntRate VARCHAR(45),
  in_CltSalesNotes VARCHAR(45),
  in_CltNxt VARCHAR(45),
  in_Score VARCHAR(45),
  in_CltNote0 VARCHAR(45),
  in_GrpNote0 VARCHAR(45),
  in_CltStartDate VARCHAR(45),
  in_CltIndGrp VARCHAR(45),
  in_CltDRNNo VARCHAR(45),
  in_CltLastListed VARCHAR(45),
  in_CltDRNNoteBatch VARCHAR(45),
  in_CltDRNStatusBatch VARCHAR(45),
  in_CltAccts VARCHAR(45),
  in_CltDRNPmtBatch VARCHAR(45),
  in_CltListed VARCHAR(45),
  in_CltDRNRemitBatch VARCHAR(45),
  in_CltColl VARCHAR(45),
  in_CltDRNShortName VARCHAR(45),
  in_CltLiq VARCHAR(45),
  in_CltStMonth VARCHAR(45),
  in_CltStComH VARCHAR(45),
  in_CltStBill VARCHAR(45),
  in_CltAR91 VARCHAR(45),
  in_CltStPdHere VARCHAR(45),
  in_CltStComD VARCHAR(45),
  in_CltStPrevB VARCHAR(45),
  in_CltStPdDir VARCHAR(45),
  in_CltStComT VARCHAR(45),
  in_CltOwes VARCHAR(45),
  in_CltStHST VARCHAR(45),
  in_CltOwesTtl VARCHAR(45),
  in_CltSalesFull VARCHAR(45),
  in_CltSalesTitle VARCHAR(45),
  in_CltSalesExt VARCHAR(45),
  in_CltSalesEmail VARCHAR(45),
  in_CltIntRate2 VARCHAR(45),
  in_LE3 VARCHAR(45),
  in_LE4 VARCHAR(45)
)
BEGIN
	INSERT INTO us06_sales
  (
    salesUID, userUID, companyUID, dateAdded, addedBy, 

    RevPanel, CltID, CltBill, CltInv, CltScrn, CltGST, CltStmt, CltLgl, CltCrBu, CltClosed, CltTrust, CltBank, CltTransit, CltAcct, CltNo, CltGrpNo,
    CltCt1, CltCt1Title, CltCt1Note, CltName, CltCt2, CltCt2Title, CltCt2Note, CltAdd1, CltCt3, CltCt3Title, CltCt3Note, CltAdd2, CltInstructions, CltCity,
    CltProv, CltPCod, CltTel1, CltFax, CltEmlPm, CltReview, CltRefNum, CltEmIn, CltTel2, CltEmail, CltViciList, CltTel3, CltACH, SalesNoteSum, CltImportSpec,
    CltIntDeferred, SalesStatus, CltComRate, CltSales, CltWorked, CltSpcStats, CltPrefCol, CltIntRate, CltSalesNotes, CltNxt, Score, CltNote0, GrpNote0,
    CltStartDate, CltIndGrp, CltDRNNo, CltLastListed, CltDRNNoteBatch, CltDRNStatusBatch, CltAccts, CltDRNPmtBatch, CltListed, CltDRNRemitBatch, CltColl,
    CltDRNShortName, CltLiq, CltStMonth, CltStComH, CltStBill, CltAR91, CltStPdHere, CltStComD, CltStPrevB, CltStPdDir, CltStComT, CltOwes, CltStHST,
    CltOwesTtl, CltSalesFull, CltSalesTitle, CltSalesExt, CltSalesEmail, CltIntRate2, LE3, LE4
  )
VALUES
  (
    in_salesUID, in_userUID, in_companyUID, CURRENT_TIMESTAMP, in_addedBy, 

    in_RevPanel, in_CltID, in_CltBill, in_CltInv, in_CltScrn, in_CltGST, in_CltStmt, in_CltLgl, in_CltCrBu, in_CltClosed, in_CltTrust, in_CltBank,
    in_CltTransit, in_CltAcct, in_CltNo, in_CltGrpNo, in_CltCt1, in_CltCt1Title, in_CltCt1Note, in_CltName, in_CltCt2, in_CltCt2Title, in_CltCt2Note,
    in_CltAdd1, in_CltCt3, in_CltCt3Title, in_CltCt3Note, in_CltAdd2, in_CltInstructions, in_CltCity, in_CltProv, in_CltPCod, in_CltTel1, in_CltFax,
    in_CltEmlPm, in_CltReview, in_CltRefNum, in_CltEmIn, in_CltTel2, in_CltEmail, in_CltViciList, in_CltTel3, in_CltACH, in_SalesNoteSum,
    in_CltImportSpec, in_CltIntDeferred, in_SalesStatus, in_CltComRate, in_CltSales, in_CltWorked, in_CltSpcStats, in_CltPrefCol, in_CltIntRate,
    in_CltSalesNotes, in_CltNxt, in_Score, in_CltNote0, in_GrpNote0, in_CltStartDate, in_CltIndGrp, in_CltDRNNo, in_CltLastListed, in_CltDRNNoteBatch,
    in_CltDRNStatusBatch, in_CltAccts, in_CltDRNPmtBatch, in_CltListed, in_CltDRNRemitBatch, in_CltColl, in_CltDRNShortName, in_CltLiq, in_CltStMonth,
    in_CltStComH, in_CltStBill, in_CltAR91, in_CltStPdHere, in_CltStComD, in_CltStPrevB, in_CltStPdDir, in_CltStComT, in_CltOwes, in_CltStHST,
    in_CltOwesTtl, in_CltSalesFull, in_CltSalesTitle, in_CltSalesExt, in_CltSalesEmail, in_CltIntRate2, in_LE3, in_LE4
  );

END